"""Run the full suite with every database-backed test actually executing.

`pytest` alone skips two independent groups when their environment is absent:
the container-backed integration modules (no Docker) and the real-database
proving tests (no `HELM_TEST_DATABASE_URL`). Both skips are silent and both
report green, which is how a suite ends up passing without ever touching a
database. Those are the only tests covering RLS, the SECURITY DEFINER keyholes,
provisioning under a non-bypass role, and the tenant name coming from the
database rather than being fabricated from the slug -- every one of which has
already hidden a real defect.

This starts one disposable container, migrates it, points both switches at it,
and runs the suite with `HELM_REQUIRE_INTEGRATION_TESTS=1` so a missing
prerequisite fails loudly instead of skipping.

    ./.venv/Scripts/python.exe scripts/run_integration_tests.py

Any extra arguments are passed through to pytest.

The container is disposable and is destroyed on exit. Nothing here can reach a
shared, staging, or production database: the URL is generated by the container.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
POSTGRES_IMAGE = "postgres:16-alpine"


def main(argv: list[str]) -> int:
    # `tests.conftest` owns the non-bypass role's name and per-run password;
    # importing them keeps this script from drifting out of step with it.
    if str(PROJECT_ROOT) not in sys.path:
        sys.path.insert(0, str(PROJECT_ROOT))

    try:
        from testcontainers.postgres import PostgresContainer
    except ImportError:
        print("testcontainers is not installed. Install requirements-dev.txt.", file=sys.stderr)
        return 1

    container = PostgresContainer(POSTGRES_IMAGE)
    try:
        container.start()
    except Exception as error:
        print(f"Could not start {POSTGRES_IMAGE}: {type(error).__name__}. Is Docker running?", file=sys.stderr)
        return 1

    try:
        sync_url = container.get_connection_url()
        async_url = sync_url.replace("postgresql+psycopg2://", "postgresql+asyncpg://")

        environment = os.environ.copy()
        environment["DATABASE_MIGRATION_URL"] = async_url
        migration = subprocess.run(
            [sys.executable, "-m", "alembic", "upgrade", "head"],
            cwd=PROJECT_ROOT,
            env=environment,
            capture_output=True,
            text=True,
            check=False,
        )
        if migration.returncode != 0:
            print(f"Alembic could not migrate the container:\n{migration.stderr[-2000:]}", file=sys.stderr)
            return migration.returncode

        # HELM_TEST_DATABASE_URL must NOT be the container's default user: that
        # user is a superuser, and RLS assertions under a BYPASSRLS role prove
        # nothing at all. tests/test_rls_integration.py refuses to run against
        # one, which is the guard that keeps those tests honest -- and is exactly
        # how this project's RLS chicken-and-egg bug stayed hidden twice.
        #
        # So provision the same non-bypass role the conftest uses and point the
        # variable at that instead.
        import asyncio

        from tests.conftest import NON_BYPASS_PASSWORD, NON_BYPASS_ROLE, _provision_non_bypass_role

        asyncio.run(_provision_non_bypass_role(async_url, NON_BYPASS_PASSWORD))

        credentials = f"{NON_BYPASS_ROLE}:{NON_BYPASS_PASSWORD}"
        app_url = async_url.replace(f"{container.username}:{container.password}", credentials, 1)
        if credentials not in app_url:
            print("Could not rewrite the container URL to the non-bypass role.", file=sys.stderr)
            return 1

        # Both switches, plus strictness -- so if either group would still skip,
        # the run fails instead of quietly reporting green.
        environment["HELM_TEST_DATABASE_URL"] = app_url
        environment["HELM_REQUIRE_INTEGRATION_TESTS"] = "1"

        return subprocess.run(
            [sys.executable, "-m", "pytest", *argv],
            cwd=PROJECT_ROOT,
            env=environment,
            check=False,
        ).returncode
    finally:
        container.stop()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
